### ISSUE TITLE
Chybejici examples

### ISSUE THREAD

**Issue by dhqcz** [tomas-kulhanek/czech-data-box#12]
Zdravim Vas a hned z uvodu dekuji za udrzovani tento knihovny.
Rad bych se zeptal na examples, o kterych se v readme zminujete. Nasel jsem nejake az ve verzi 2.0, ale ty uz bohuzel nejsou aktualni (napr. trida` TomasKulhanek\CzechDataBox\Connector\DataMessage` ve verzi 4.0 neexistuje).
Prehlizim neco nebo mohl bych poprosit o nakopnuti, jedna se mi o druhy argument metody Manager.
Diky!

**Comment by tomas-kulhanek** [comment]
@dhqcz  díky moc za upozornění. Kdyžtak PR je vítáno :) 

o jakou situaci přesněji jde? Sample zatím jde využít z testů https://github.com/tomas-kulhanek/czech-data-box/blob/main/tests/Integration/DataMessageTest.php

**Comment by dhqcz** [comment]
Dekuji za bleskovou odpoved, testy jsem prehledl a vse potrebne v nich vidim, perfektni. :)

**Comment by tomas-kulhanek** [comment]
myslím, že testy jsou lepší než examples :)
