### ISSUE TITLE
ISDSSearch3 - bez změny attr $page vrací výsledky až z 1. stránky

### ISSUE THREAD

**Issue by dhqcz** [tomas-kulhanek/czech-data-box#13]
Ahoj,
setkali jste se prosím s tím, že endpointu ISDSSearch3 poskytnete validní query, která má vracet výsledky, dokonce je uveden správný počet výsledků (totalCount), ale v results nic není?
Konkrétní příklad níže.
Za nakopnutí budu rád, díky! :)

![image](https://user-images.githubusercontent.com/4020490/154671574-54e5c061-0b85-480c-83ad-54770ef47332.png)

**Comment by tomas-kulhanek** [comment]
@dhqcz  ahoj,  zde bych viděl 2 důvody. 
- je špatně mapování
- opravdu to nic nenašlo :)
Co máš v `$response` zde https://github.com/tomas-kulhanek/czech-data-box/blob/main/src/Connector.php#L289 ?

**Comment by dhqcz** [comment]
Díky za bleskovou odpověď. Po odeslání issue jsem si všiml, že v response je currentCount = 0, takže hodnota result je správná, nemá tam nic být.
Problém je v tom, že defaultní hodnota property $page v requestu ISDSSearch3 je 1, pokud nastavím u requestu hodnotu na 0, už se to chová podle očekávání a výsledek mi to vrací. Takže pokud člověk nesáhne na properties page a pageSize, dostává výsledky od 21. záznamu. Takže takový feedback, možná by stálo za úvahu nastavit defaultní hodnotu property $page na 0. :)

**Comment by tomas-kulhanek** [comment]
@dhqcz  mohu poprosit o pull request?

**Comment by dhqcz** [comment]
https://github.com/tomas-kulhanek/czech-data-box/pull/14
