### ISSUE TITLE
Jak stáhnout .zfo soubor a přílohy z přijaté zprávy?

### ISSUE THREAD

**Issue by zdeneklapes** [tomas-kulhanek/czech-data-box#22]
### Library version(s) affected

8.3.4

### Description

Dobrý den, můžeme prosím poskytnout příklad kódu, který stáhne .zfo soubor a všechny přílohy z přijaté zprávy?

**Comment by tomas-kulhanek** [comment]
@zdeneklapes  Dobrý den, 
asi moc nechápu. Pokud chcete poskytnout někomu dalšímu příklad, tak se nemusíte ptát. Pokud chcete příklad odemne, tak máte 2 možnosti. 

- napsat si parser, který ZFO soubor převede na FO soubor, který je již jen podepsaný XML soubor a z něj si již přílohy v base64 vytáhnete
- nebo použijete jednu z metod jako je například `messageDownload` a následně `$response->getReturnedMessage()->getDataMessage()->getFiles()`
- originál zprávy (ZFO) stáhnete pomocí `signedMessageDownload` či `signedSentMessageDownload`

Pokud ale mohu doporučit, tak si na své úložiště stahujte jen ZFO soubor, který obsahuje podpis i časové razítko a kdykoliv jej můžete konvertovat do listinné podoby skrze CzechPoint. Také z něj vytáhnete časové razítko, přílohy atp. 

Vše toto je dostupné v dokumentaci od ISDS, kdy názvy metod jsou převzaté.

**Comment by zdeneklapes** [comment]
@tomas-kulhanek Dobrý den, pane Kulhanku,

děkuji moc, to mi vyřešilo, co jsem potřeboval!

Jeste prosím, kde je možné najít složku examples, která je zmíněna v README.md?

**Comment by tomas-kulhanek** [comment]
@zdeneklapes Bohužel není v mojich silách složku udržovat a při refactoringu jsem ji odebral. Rozhodně děkuji za informaci, z Readme to odeberu. 

Pro nejvíc příkladů stačí využívat dokumentaci přímo ISDS, jelikož v knihovně jejich naming přebírám.
